spring.application.name=projeto
spring.profiles.active=dev
spring.jpa.open-in-view=true
security.client-id=${CLIENT_ID:myclientid}
security.client-secret=${CLIENT_SECRET:myclientsecret}
security.jwt.duration=${JWT_DURATION:86400}
cors.origins=${CORS_ORIGINS:http://localhost:3000, http://localhost:5173, http://192.168.15.188:8080}
